*
* $Id: ludat1-cern.inc,v 1.1.1.1 2013/02/15 23:10:27 rclsa Exp $
*
* $Log: ludat1-cern.inc,v $
* Revision 1.1.1.1  2013/02/15 23:10:27  rclsa
* creation of wmass_powheg_interface
*
* Revision 1.1.1.1  1996/03/08 17:32:19  mclareni
* jetset74
*
*
#ifndef CERNLIB_JETSET74_LUDAT1_INC
#define CERNLIB_JETSET74_LUDAT1_INC
*
*
* ludat1.inc
*
      COMMON/LUDAT1/MSTU(200),PARU(200),MSTJ(200),PARJ(200)
      SAVE /LUDAT1/

#endif
