*
* $Id: lujets-cern.inc,v 1.1.1.1 2013/02/15 23:10:27 rclsa Exp $
*
* $Log: lujets-cern.inc,v $
* Revision 1.1.1.1  2013/02/15 23:10:27  rclsa
* creation of wmass_powheg_interface
*
* Revision 1.1.1.1  1996/03/08 17:32:19  mclareni
* jetset74
*
*
#ifndef CERNLIB_JETSET74_LUJETS_INC
#define CERNLIB_JETSET74_LUJETS_INC
*
*
* lujets.inc
*
      COMMON/LUJETS/N,K(4000,5),P(4000,5),V(4000,5)
      SAVE /LUJETS/

#endif
